title: Tomiwa's Portfolio
description: A portfolio for the collection of my projects
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
resume:
  pdf_url: 
  docx_url: Documents/Tomiwa Oladejo.docx
