title: Tomiwa's Portfolio
description: A portfolio for my collection of projects
show_downloads: True
google_analytics:
theme: jekyll-theme-architect
github:
  zip_url: https://github.com/Tomiwa-Oladejo/Portfolio/blob/main/Documents/download.pdf
