title: Tomiwa's Portfolio
description: A portfolio showcasing projects
show_downloads: True
google_analytics:
theme: jekyll-theme-architect
github:
  zip_url: https://github.com/Tomiwa-Oladejo/Portfolio/blob/main/Documents/Tomiwa_Oladejo.pdf
